version: 2
updates:
  # NPM packages
  - package-ecosystem: 'npm'
    directory: '/tooling/api'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
  - package-ecosystem: 'npm'
    directory: '/tooling/cli/node'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'

  # Tooling
  - package-ecosystem: 'cargo'
    directory: '/tooling/cli'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
  - package-ecosystem: 'cargo'
    directory: '/tooling/bundler'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
  - package-ecosystem: 'cargo'
    directory: '/tooling/webdriver'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'

  # Core
  - package-ecosystem: 'cargo'
    directory: '/core/tauri'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-build'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-codegen'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-macros'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-runtime'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-runtime-wry'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
  - package-ecosystem: 'cargo'
    directory: '/core/tauri-utils'
    schedule:
      internal: 'daily'
    labels:
      - 'type: chore'
